name: visitbih_mobile
description: Application for exploring and reading about Bosnia and Herzegovina.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_drawing: ^1.0.0
  http: ^0.13.4
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.9.3
  carousel_slider: ^4.1.1
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  firebase_analytics: ^9.1.9
  flutter_local_notifications: ^9.6.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

  uses-material-design: true

  assets:
    - assets/images/map-3d-connect.png
    - assets/images/cilim.jpg
    - assets/images/logo-visitbih.png
    - assets/images/loader-waiting.gif

